### ISSUE TITLE
http://publicportal.rest.powerschool.pearson.com/xsd is down

### ISSUE THREAD

**Issue by reteps** [powerapi/powerapi-php#12]
http://publicportal.rest.powerschool.pearson.com/xsd is not a valid ip anymore. Is there a new api?

**Comment by unlobito** [comment]
Hi there. This was never a valid URL. It's merely used as a namespace for the XML/SOAP requests made to PowerSchool. https://www.informit.com/articles/article.aspx?p=169106&seqNum=2 has an explanation on how SOAP namespaces work.
