### ISSUE TITLE
No way to retrieve total possible score on assignment

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [powerapi/powerapi-php#5]
There is no predefined way to get the total possible score on an assignment to accompany the `score`. It is *sometimes* possible to find this value via `100*$assignment->score/$assignment->percent`, however this will not work if a student received a grade of `0%` on an assignment, in this case it is impossible to calculate the total possible points.

**Comment by henriwatson** [comment]
Unfortunately, the PowerSchool API does not return the actual maximum score for the assignment.

Here's an example of the data returned by the API for an assignment:
```
[1] => stdClass Object
    (
        [assignmentId] => 98227
        [collected] => false
        [comment] => 
        [exempt] => false
        [id] => 1919903
        [late] => false
        [letterGrade] => 80
        [missing] => false
        [percent] => 80
        [score] => 40
        [scoretype] => 0
    )
```

As you can see, there's unfortunately no way to find the maximum score other than guessing (as PowerAPI currently does).

**Comment by The-Penultimate-Defenestrator** [comment]
What is the "PowerSchool API" you're referring to, besides this one?

**Comment by henriwatson** [comment]
The /pearson-rest/ endpoints used by the mobile apps (which PowerAPI uses to grab information from the server).

You can find more information on the services exposed by pearson-rest at http://sales.powerschool.com/pearson-rest/services/listServices (or by looking through the PowerAPI source code).

**Comment by The-Penultimate-Defenestrator** [comment]
Ok, thanks.
